### PR TITLE
Miscellaneous fixes

### LINKED ISSUE #62: New storage blocks aren't specifically named when using /ppl
A pearl was stored in a barrel and returned https://i.imgur.com/A9JBnUR.png rather than a name like it does for other blocks.

If you wanted a quick and easy solution, adding them to wherever the list already exists should be sufficient. But a potentially more entertaining solution could be to look up the actual name of the block, so things like wordbanked chests actually showed their name via /ppl, if that's at all possible. It would help make another place that wordbank could be visible to help encourage more wordbank usage as well as perhaps provide some entertainment for the involved players.

### PR DESCRIPTION
**Pull request by squareblob**
1) `BlockHolder::getname()` : Fixes #62. Returns the block type for any block [and the blocks custom display name](https://i.imgur.com/VXNYD0x.png) (if applicable).
2) `PlayerHolder::getName()` : Show PlayerHolder name in aqua for a bit more clarity.
3) `EntityHolder` : Allow storing pearls in itemframes. Behavior before this commit was that pearls can be placed in item frames yet no PearlMovedEvent is triggered and the pearl is freed upon validation attempt. 
4) Fixes a bug where shift clicking into a furnace updates the pearl holder to the furnace even though the pearl is not actually transferred.

### CODE REVIEW

File: src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java [hunk 1]
```diff
@@ -424,6 +446,20 @@ public void onPlayerPickupPearl(EntityPickupItemEvent e) {
 		}
 	}
 
+	/**
+	 * Listen for pearl being moved to item frame
+	 * @param event
+	 */
+	@EventHandler(priority = EventPriority.NORMAL, ignoreCancelled = true)
+	public void onPlayerInteractEntity(PlayerInteractEntityEvent event) {
```
Comment (Maxopoly) [inline src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java:454]: Is there some other existing listener that handles the item frame being broken or the pearl being removed or how does that work?

Comment (squareblob) [reply src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java:454]: Anytime the pearl leaves the item frame, `ItemSpawnEvent`  should be [called](https://github.com/CivClassic/ExilePearl/blob/c02223f95968b9db48861156d9db8adf56db84b8/src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java#L187).

Comment (Maxopoly) [reply src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java:454]: Ah, neat

**Comment by Maxopoly** [comment]
Nice work
